// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2uoeiFxZp5eJu9kLsbUJAEnoSpvuYEzU',
    appId: '1:145478012789:web:0e21c8cc64afcb19fb0d3c',
    messagingSenderId: '145478012789',
    projectId: 'ehaldhar-369fe',
    authDomain: 'ehaldhar-369fe.firebaseapp.com',
    storageBucket: 'ehaldhar-369fe.firebasestorage.app',
    measurementId: 'G-N0357PCKTG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFjru2stBOUOOCpYRheSOIEnHzryJIq3c',
    appId: '1:145478012789:android:076d17e017d9c7bcfb0d3c',
    messagingSenderId: '145478012789',
    projectId: 'ehaldhar-369fe',
    storageBucket: 'ehaldhar-369fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXmtdHhnh7cE5gwZBITe2HMCXvyuA5yfA',
    appId: '1:145478012789:ios:1440ee2949e289d9fb0d3c',
    messagingSenderId: '145478012789',
    projectId: 'ehaldhar-369fe',
    storageBucket: 'ehaldhar-369fe.firebasestorage.app',
    iosBundleId: 'com.example.ehaldhar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXmtdHhnh7cE5gwZBITe2HMCXvyuA5yfA',
    appId: '1:145478012789:ios:1440ee2949e289d9fb0d3c',
    messagingSenderId: '145478012789',
    projectId: 'ehaldhar-369fe',
    storageBucket: 'ehaldhar-369fe.firebasestorage.app',
    iosBundleId: 'com.example.ehaldhar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2uoeiFxZp5eJu9kLsbUJAEnoSpvuYEzU',
    appId: '1:145478012789:web:b0e9abd3ebc4b376fb0d3c',
    messagingSenderId: '145478012789',
    projectId: 'ehaldhar-369fe',
    authDomain: 'ehaldhar-369fe.firebaseapp.com',
    storageBucket: 'ehaldhar-369fe.firebasestorage.app',
    measurementId: 'G-7KR7NCGH0N',
  );

}